title: CSG TEST Intergovernmental Software Collaborative
description: Helping governments build and share software to solve their common problems.
url: https://csg2760.github.io/softwarecollaborative.org
remote_theme: pmarsceill/just-the-docs

links:
  home: /
  collaboratives: /collaboratives/
  case-studies: /publications/
